version: 2

project_name: acv-inq

builds:
  - id: linux-amd64
    binary: acv-inq
    goos: [linux]
    goarch: [amd64]
    skip: true

  - id: linux-musl
    binary: acv-inq
    goos: [linux]
    goarch: [amd64]
    skip: true

  - id: darwin-amd64
    binary: acv-inq
    goos: [darwin]
    goarch: [amd64]
    skip: true

  - id: darwin-arm64
    binary: acv-inq
    goos: [darwin]
    goarch: [arm64]
    skip: true

  - id: windows-amd64
    binary: acv-inq
    goos: [windows]
    goarch: [amd64]
    skip: true

archives:
  - id: linux-amd64
    builds: [linux-amd64]
    format: tar.gz
    name_template: "{{ .ProjectName }}-linux-amd64"
    files:
      - src: dist/acv-inq-linux-amd64
        dst: acv-inq
      - README.md
      - LICENSE
      - install.sh

  - id: linux-musl
    builds: [linux-musl]
    format: tar.gz
    name_template: "{{ .ProjectName }}-linux-amd64-musl"
    files:
      - src: dist/acv-inq-linux-amd64-musl
        dst: acv-inq
      - README.md
      - LICENSE
      - install.sh

  - id: darwin-amd64
    builds: [darwin-amd64]
    format: tar.gz
    name_template: "{{ .ProjectName }}-darwin-amd64"
    files:
      - src: dist/acv-inq-darwin-amd64
        dst: acv-inq
      - README.md
      - LICENSE
      - install.sh

  - id: darwin-arm64
    builds: [darwin-arm64]
    format: tar.gz
    name_template: "{{ .ProjectName }}-darwin-arm64"
    files:
      - src: dist/acv-inq-darwin-arm64
        dst: acv-inq
      - README.md
      - LICENSE
      - install.sh

  - id: windows-amd64
    builds: [windows-amd64]
    format: zip
    name_template: "{{ .ProjectName }}-windows-amd64"
    files:
      - src: dist/acv-inq-windows-amd64.exe
        dst: acv-inq.exe
      - README.md
      - LICENSE
      - install.bat

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "🐛 Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "📖 Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: "🔧 Other"
      order: 999

release:
  github:
    owner: user
    name: activity-inquirer
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Activity Inquirer {{ .Tag }}
    
    ### 🚀 Funcionalidades
    - **Rastreamento de atividades**: Interface intuitiva para registrar o que você está fazendo
    - **Modo daemon**: Execução automática em background com intervalos configuráveis
    - **Visualizador avançado**: Timeline das atividades com horários e intervalos
    - **Configurações flexíveis**: Interface gráfica para personalizar comportamento
    - **Temas Gruvbox**: Dark e Light themes profissionais
    - **Fontes Nerd Font**: FiraCode com ícones e ligaduras embarcadas
    - **Cross-platform**: Funciona em Linux, macOS e Windows
    
    ### 📦 Downloads
    Escolha o arquivo apropriado para seu sistema:
    
  footer: |
    ### 🛠️ Instalação
    1. Baixe o arquivo para seu sistema
    2. Extraia o conteúdo
    3. Execute `./install.sh` (Linux/macOS) ou `install.bat` (Windows)
    
    ### 📖 Uso
    ```bash
    # Visualizar atividades
    acv-inq
    
    # Registrar nova atividade
    acv-inq --inquiry
    
    # Configurações
    acv-inq --settings
    
    # Modo daemon
    acv-inq --daemon
    ```
    
    **Tamanho dos binários**: ~17-20MB (incluindo fontes Nerd Font embarcadas)
    **Requisitos**: Nenhum! Todos os binários são autônomos.

git:
  tag_sort: -version:refname

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: 'checksums.txt'

dist: dist
